version: '3'

tasks:
  build:
    desc: Build all binaries
    cmds:
      - echo "Building parking-app..."
      - go build -o bin/parking-app parking-app/main.go
      - echo "Build completed!"

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "Cleaning build artifacts..."
      - rm -rf bin/
      - echo "Clean completed!"

  bench:
    desc: benchmark backend implementation in multiple version
    cmds:
      - go test -race -bench=. -benchmem ./test

  coverage-check:
    desc: check backend implementation code coverage
    cmds:
      - go test -coverpkg=github.com/khafidprayoga/parking-app/internal/backend -covermode=atomic -coverprofile=coverage.out ./test/...