version: '3'

tasks:
  build:
    desc: Build all binaries
    cmds:
      - echo "Building parking-app..."
      - go build -o bin/parking-app cmd/main.go
      - echo "Build completed!"

  clean:
    desc: Clean build artifacts
    cmds:
      - echo "Cleaning build artifacts..."
      - rm -rf bin/
      - echo "Clean completed!" 